; window.replace = function () { return '' }; (function (k, l) {
    var f, g = { getQuery: function (a) { a = location.href.match(RegExp("[?&]" + a + "=([^&]+)", "i")); return (null == a || 1 > a.length ? "" : a[1]) } }, h = function () { this.key = "UNION"; this.cKey = "Union"; this.store = k.localStorage; this.launch() }; h.prototype = { launch: function () {
        var a = g.getQuery("allianceid"), c = g.getQuery("sid"), b = g.getQuery("ouid") || g.getQuery("actouid"); (a && c ? (f = { AllianceID: a, SID: c, OUID: b }, this.setStore(f), this.setCooki(f)) : this.referrer(a, c, b) || (a = this.getStore(this.key)) && (a.st && new Date(a.st) && 0 < (new Date).getTime() -
a.st) && this.store.removeItem(this.key)); if ("undefined" === typeof window.__union) window.__union = [], window.__union.push = function (a) { a && (a.callback && "function" == typeof a.callback) && a.callback() }; else { a = window.__union.length || 0; for (c = 0; c < a; c++) (b = window.__union[c]) && (b.callback && "function" == typeof b.callback) && b.callback() } 
    }, dateNext: function (a) { return new Date((new Date).getTime() + 864E5 * a) }, setStore: function (a, c) {
        var b = this.dateNext(7), e = (/^(\w[^#]+)/); a.AllianceID = (a.AllianceID.match(e) ? a.AllianceID.match(e)[0] :
a.AllianceID); a.SID = (a.SID.match(e) ? a.SID.match(e)[0] : a.SID); b = { data: a, timeout: b.getFullYear() + "-" + (b.getMonth() + 1) + "-" + b.getDate() + " " + b.getHours() + ":" + b.getMinutes() + ":" + b.getSeconds(), st: b.getTime() }; this.store.setItem(this.key, JSON.stringify(b))
    }, getStore: function (a) { var c; a = this.store.getItem(a); try { c = JSON.parse(a) } catch (b) { c = null } return c }, setCooki: function (a, c) {
        var b = c || 7, e = new Date, d = (/^(\w[^#]+)/); e.setTime(e.getTime() + 864E5 * b); a.AllianceID = (a.AllianceID.match(d) ? a.AllianceID.match(d)[0] : a.AllianceID);
        a.SID = (a.SID.match(d) ? a.SID.match(d)[0] : a.SID); document.cookie = this.cKey + "=" + ("OUID=" + a.OUID + "&AllianceID=" + a.AllianceID + "&SID=" + a.SID) + ";path=/;expires=" + e.toUTCString() + ";domain=" + window.location.hostname.split(".").slice(-2).join(".") || "ctrip.com"
    }, getCooki: function (a) { a = document.cookie.match(RegExp("(^| )" + a + "=([^;]*)(;|$)")); return (null != a ? unescape(a[2]) : null) }, referrer: function (a, c, b) {
        var e = location.host, d = document.referrer; f = null; if (e && -1 === d.indexOf(e)) {
            d = d.replace("http://", "").replace("https://",
"").split("/")[0].toLowerCase(); -1 < d.indexOf("baidu") && (a = a || "4897", c = c || "353693", b = b || ""); -1 < d.indexOf("google") && (a = a || "4899", c = c || "353694", b = b || ""); -1 < d.indexOf("soso.com") && (a = a || "4900", c = c || "353696", b = b || ""); -1 < d.indexOf("sogou") && (a = a || "4901", c = c || "353698", b = b || ""); -1 < d.indexOf("m.so.com") && (a = a || "5376", c = c || "353699", b = b || ""); -1 < d.indexOf("so.360") && (a = a || "5376", c = c || "353700", b = b || ""); -1 < d.indexOf("bing.com") && (a = a || "4902", c = c || "353701", b = b || ""); -1 < d.indexOf("yahoo") && (a = a || "4903", c = c || "353703",
b = b || ""); -1 < d.indexOf("youdao") && (a = a || "4904", c = c || "353704", b = b || ""); if (-1 < d.indexOf("jike.com") || -1 < d.indexOf("babylon.com") || -1 < d.indexOf("ask.com") || -1 < d.indexOf("avg.com") || -1 < d.indexOf("easou.com") || -1 < d.indexOf("panguso.com") || -1 < d.indexOf("yandex.com")) a = a || "5376", c = c || "353700", b = b || ""; -1 < d.indexOf("soso") && (a = a || "4900", c = c || "353696", b = b || ""); -1 < d.indexOf("so.com") && (a = a || "5376", c = c || "353699", b = b || ""); -1 < d.indexOf("sm.cn") && (a = a || "18887", c = c || "447459", b = b || ""); -1 < d.indexOf("duckduckgo") && (a =
a || "20080", c = c || "450748", b = b || ""); a && c && (f = { AllianceID: a, SID: c, OUID: b }, this.setStore(f), this.setCooki(f))
        } return f
    } 
    }; try { (-1 != location.hostname.toLowerCase().indexOf("qa.nt.ctripcorp.com") || "m.ctrip.com" == location.hostname.toLowerCase()) && new h } catch (m) { } 
})(window);